name: 'etl_synthea_dbt'
version: '1.0.0'
config-version: 2

profile: 'etl_synthea_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  etl_synthea_dbt:
    omop:
      +materialized: table
    staging:
      schema: stg
      +materialized: view

# dbt run --select +omop --exclude tag:mapping