version: 2

sources:
  - name: synthea
    schema: source
    tables:
      - name: patients
      - name: encounters
      - name: providers
      - name: conditions
      - name: allergies
      - name: observations
      - name: procedures
      - name: devices
      - name: medications
      - name: immunizations
  - name: vocab
    schema: cdm
    tables:
      - name: concept
      - name: concept_relationship
      - name: concept_ancestor
      - name: source_to_concept_map
      - name: vocabulary
