version: 2

sources:
  - name: synthea
    schema: source
    tables:
      - name: patients
      - name: encounters
      - name: providers
      - name: conditions
  - name: vocab
    schema: cdm
    tables:
      - name: concept
      - name: concept_relationship
      - name: source_to_concept_map
